import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import Balancer from "react-wrap-balancer";

import { Input } from "@/components/ui/Input";
import { Button } from "@/components/ui/Button";
import { ModeToggle } from "@/components/mode-toggle";
// import { Event } from "@/components/ui/Event";
import AlertDialogEvent from "@/components/ui/AlertDialogEvent";
import { useState } from "react";

const Dashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>River</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full px-4 py-2">
        <header className="flex items-center justify-between border-b border-slate-500 pb-2">
          <Link href="/">River</Link>
          <ModeToggle />
          <AlertDialogEvent />
        </header>
        <div className="h-max w-full px-8 py-4">
          <h1 className="text-2xld pt-6 font-bold lg:text-4xl">Your Events</h1>
          <p className="flex-box w-full py-2 text-xl text-[#6F6F6F] dark:text-slate-400">
            Welcome to your event dashboard. View your current, drafted, and
            archived events.
          </p>
          <div className="py-16">
            <p className="flex-box w-full justify-center pt-4 pb-4 text-center align-middle text-xl text-[#6F6F6F] dark:text-slate-400">
              You do not have any events right now. Create one to get started.
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Dashboard;
